export const CLR_AQUA_ISLAND = '#A2DED0';
export const CLR_CARRARA = '#F2F1EF';
export const CLR_GRAY = '#CCCCCC';
export const CLR_RED = 'red';
export const CLR_WHITE_TRANSPARENT = 'rgba(255,255,255,0.7)';
export const CLR_FULL_TRANSPARENT = 'rgba(255,255,255,0.0)';

export const MAIN_COLOR_DARK = '#1B6913';
export const MAIN_COLOR = '#44A139';
export const MAIN_COLOR_BRIGHT = '#C4E5C1';

export const CLR_SCREEN_BACKGROUND = CLR_CARRARA;
export const CLR_CAROUSEL_BACKGROUND = MAIN_COLOR_BRIGHT;
export const CLR_CATEGORY_BACKGROUND = MAIN_COLOR_BRIGHT;
export const CLR_VK_BACKGROUND = MAIN_COLOR_BRIGHT;

export const CLR_MENU_BACKGROUND_SELECTED = CLR_CARRARA;
export const CLR_MENU_BACKGROUND_NOT_SELECTED = MAIN_COLOR;
export const CLR_MENU_ICON_SELECTED = MAIN_COLOR_DARK;
export const CLR_MENU_ICON_NOT_SELECTED = CLR_CARRARA;

export const CLR_HEADER_BACKGROUND = MAIN_COLOR;
export const CLR_HEADER_TEXT = CLR_CARRARA;

export const CLR_NO_LOGO = MAIN_COLOR_BRIGHT;

export const CLR_SEARCH_BUTTON = CLR_CARRARA;
export const CLR_SEARCH_BACKGROUND = CLR_CARRARA;
export const CLR_SEARCH_TEXT = MAIN_COLOR_DARK;

export const CLR_DISCOUNT_TEXT = CLR_RED;
export const CLR_FAVORITE_ICON = CLR_RED;

export const CLR_LABEL_BACK = CLR_WHITE_TRANSPARENT;
